version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    container_name: user-service
    networks:
      - my_network

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    container_name: order-service
    networks:
      - my_network


  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "100:100"
    networks:
      - my_network
      
networks:
  my_network:
    driver: bridge
